master = \
{'Xrc': False,
 'adsorption_model': 'HK',
 'algorithm_parameters': {'all_parents_to_new_gen': False,
                          'crossover_probability': 1.0,
                          'crossover_type': 'uniform',
                          'elit_ratio': 0.01,
                          'individual_mutation_probability': 0.1,
                          'initial_population_size': None,
                          'max_iteration_without_improv': 250,
                          'max_mutations': 50,
                          'max_num_iteration': 2,
                          'mutation_algorithm': 'mutcoinflip',
                          'mutation_probability': 1.0,
                          'obj_func_cutoff': 100.0,
                          'parents_portion': 0.6,
                          'population_size': 50,
                          'stochastic_method': 'unique_uniform',
                          'stochastic_pick_ratio': 0.1},
 'cont_file_writing_frequency': 250,
 'delta_logarithm': False,
 'dft_deviation_coefs': {'default': 1.0},
 'dft_deviation_penalty_model': 'quadratic',
 'dft_energy_file': '/Users/mikval/niflheim/MKMV/CO_hyd/gamkm/examples/dft_and_exp_data/dft_energies.py',
 'energy_bounds': {'adsorbate': 0.3, 'gas': 0.3, 'transition_state': 0.3},
 'fractional_pressures': {'CO_g': 0.3333333333333333,
                          'H2_g': 0.6666666666666666},
 'func_exec_report_file': 'func_exec_report.txt',
 'function_timeout': {'aai': 6.5, 'no_aai': 5.0},
 'init_covs': {'T_cutoff': 50.0, 'p_cutoff': 100000.0, 'type': 'closest'},
 'integration_time_length': 100000000.0,
 'landscape_energy_type': 'E',
 'logfile': 'eval.log',
 'max_aai_penalty': 0.05,
 'ode_algorithm': 'Radau',
 'ode_scale_factor': 10000.0,
 'ode_solver': 'super_stiff',
 'ode_tols': (1e-06, 1e-09),
 'plotted_rxns': {'CH4_CHO': ['COads',
                              'H2to2H',
                              'CO,HtoCHO',
                              'CHO,HtoCHOH',
                              'CHOHtoCH,OH',
                              'H2to2H',
                              'CH,HtoCH2',
                              'CH2,HtoCH3',
                              'H2to2H',
                              'CH3,HtoCH4',
                              'OH,HtoH2O',
                              'H2Odes'],
                  'CH4_COH': ['COads',
                              'H2to2H',
                              'CO,HtoCOH',
                              'COHtoC,OH',
                              'C,HtoCH',
                              'H2to2H',
                              'CH,HtoCH2',
                              'CH2,HtoCH3',
                              'H2to2H',
                              'CH3,HtoCH4',
                              'OH,HtoH2O',
                              'H2Odes'],
                  'CH4_COH_CHOH': ['COads',
                                   'H2to2H',
                                   'CO,HtoCOH',
                                   'COH,HtoCHOH',
                                   'CHOHtoCH,OH',
                                   'H2to2H',
                                   'CH,HtoCH2',
                                   'CH2,HtoCH3',
                                   'H2to2H',
                                   'CH3,HtoCH4',
                                   'OH,HtoH2O',
                                   'H2Odes'],
                  'MeOH_CH2O': ['COads',
                                'H2to2H',
                                'CO,HtoCHO',
                                'CHO,HtoCH2O',
                                'H2to2H',
                                'CH2O,HtoCH3O',
                                'CH3O,HtoCH3OH'],
                  'MeOH_CHO_CHOH': ['COads',
                                    'H2to2H',
                                    'CO,HtoCHO',
                                    'CHO,HtoCHOH',
                                    'H2to2H',
                                    'CHOH,HtoCH2OH',
                                    'CH2OH,HtoCH3OH'],
                  'MeOH_COH': ['COads',
                               'H2to2H',
                               'CO,HtoCOH',
                               'COH,HtoCHOH',
                               'H2to2H',
                               'CHOH,HtoCH2OH',
                               'CH2OH,HtoCH3OH']},
 'printed_coverages': ['CO_s', 'H_h'],
 'progress_bar': False,
 'read_continuation_population': False,
 'reference_states': ['CO_g', 'H2O_g', 'H2_g'],
 'rxn_plot_params': {'Tp': ((448.15, 15000), (598.15, 15000)),
                     'products': ['CH4_g', 'CH3OH_g', 'H2O_g'],
                     'reactants': ['CO_g', 'H2_g']},
 'rxns': {'C,HtoCH': {'l': ['C_s', 'H_h'],
                      'm': ['C-H_s', '*_h'],
                      'r': ['CH_s', '*_h']},
          'CH,HtoCH2': {'l': ['CH_s', 'H_h'],
                        'm': ['H-CH_s', '*_h'],
                        'r': ['CH2_s', '*_h']},
          'CH2,HtoCH3': {'l': ['CH2_s', 'H_h'],
                         'm': ['CH2-H_s', '*_h'],
                         'r': ['CH3_s', '*_h']},
          'CH2O,HtoCH3O': {'l': ['CH2O_s', 'H_h'],
                           'm': ['H-CH2O_s', '*_h'],
                           'r': ['CH3O_s', '*_h']},
          'CH2OH,HtoCH3OH': {'l': ['CH2OH_s', 'H_h'],
                             'm': ['H-CH2OH_s', '*_h'],
                             'r': ['CH3OH_g', '*_h', '*_s']},
          'CH3,HtoCH4': {'l': ['CH3_s', 'H_h'],
                         'm': ['CH3-H_s', '*_h'],
                         'r': ['CH4_g', '*_h', '*_s']},
          'CH3O,HtoCH3OH': {'l': ['CH3O_s', 'H_h'],
                            'm': ['CH3O-H_s', '*_h'],
                            'r': ['CH3OH_g', '*_h', '*_s']},
          'CHO,HtoCH2O': {'l': ['CHO_s', 'H_h'],
                          'm': ['H-CHO_s', '*_h'],
                          'r': ['CH2O_s', '*_h']},
          'CHO,HtoCHOH': {'l': ['CHO_s', 'H_h'],
                          'm': ['HCO-H_s', '*_h'],
                          'r': ['CHOH_s', '*_h']},
          'CHOH,HtoCH2OH': {'l': ['CHOH_s', 'H_h'],
                            'm': ['H-CHOH_s', '*_h'],
                            'r': ['CH2OH_s', '*_h']},
          'CHOHtoCH,OH': {'l': ['CHOH_s', '*_s'],
                          'm': ['CH-OH_s', '*_s'],
                          'r': ['CH_s', 'OH_s']},
          'CO,HtoCHO': {'l': ['CO_s', 'H_h'],
                        'm': ['H-CO_s', '*_h'],
                        'r': ['CHO_s', '*_h']},
          'CO,HtoCOH': {'l': ['CO_s', 'H_h'],
                        'm': ['CO-H_s', '*_h'],
                        'r': ['COH_s', '*_h']},
          'COH,HtoCHOH': {'l': ['COH_s', 'H_h'],
                          'm': ['H-COH_s', '*_h'],
                          'r': ['CHOH_s', '*_h']},
          'COHtoC,OH': {'l': ['COH_s', '*_s'],
                        'm': ['C-OH_s', '*_s'],
                        'r': ['C_s', 'OH_s']},
          'COads': {'l': ['CO_g', '*_s'], 'r': ['CO_s']},
          'H2Odes': {'l': ['H2O_s'], 'r': ['H2O_g', '*_s']},
          'H2to2H': {'l': ['H2_g', '*_h', '*_h'], 'r': ['H_h', 'H_h']},
          'OH,HtoH2O': {'l': ['OH_s', 'H_h'],
                        'm': ['H-OH_s', '*_h'],
                        'r': ['H2O_s', '*_h']}},
 'save_timelapse': True,
 'spectra_coef': 10.0,
 'spectra_dir': '/Users/mikval/niflheim/MKMV/CO_hyd/gamkm/examples/dft_and_exp_data/spectra_march2',
 'steps': 10000,
 'strict_ode_tols': (1e-09, 1e-12),
 'theta0': None,
 'timeout_objective_function': 150.0,
 'total_pressure': 15000.0}
